# Generated by Django 5.0.1 on 2024-02-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=7
                    ),
                ),
                ("dob", models.DateField(default=None)),
                ("contact", models.CharField(blank=True, max_length=150, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
