# Generated by Django 5.0.1 on 2024-02-15 11:42

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="avatar",
            field=models.FileField(
                blank=True,
                upload_to=collection.models.user_directory_path,
                validators=[collection.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(),
        ),
    ]
